-- ============================================================
-- RAG Content Production System — Supabase Schema
-- Run this in the Supabase SQL Editor (supabase.com > project > SQL Editor)
-- ============================================================

-- Enable required extensions
create extension if not exists "pgcrypto";    -- for gen_random_uuid()
create extension if not exists "vector";       -- for pgvector (RAG embeddings)

-- ============================================================
-- 1. CLIENTS
-- ============================================================
create table clients (
  id uuid primary key default gen_random_uuid(),
  brand_name text not null,
  business_type text not null,                  -- 'lead_generation', 'ecommerce', 'marketplace'
  industry text not null,
  market text not null default 'AU',
  currency text not null default 'AUD',
  website_url text not null,
  target_audience_summary text,
  gsc_property_id text,                         -- for GSC API integration (update pipeline)
  ga4_property_id text,
  ga4_conversion_events jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- 2. VOICE PROFILES
-- Auto-generated by Claude during client onboarding.
-- One per client (regenerate every 6-12 months).
-- ============================================================
create table voice_profiles (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  sentence_patterns text,
  vocabulary_preferences text,
  structure_patterns text,
  tone_description text,
  opening_style text,
  closing_style text,
  proof_style text,
  sample_passages text,
  generated_at timestamptz not null default now(),
  last_updated timestamptz not null default now(),

  constraint uq_voice_profiles_client unique (client_id)
);

-- ============================================================
-- 3. CONTENT TYPES
-- Defines structure, rules, and quality criteria per content type.
-- Shared across all clients.
-- ============================================================
create table content_types (
  id uuid primary key default gen_random_uuid(),
  type_name text not null,                      -- 'Asset Class Page'
  type_slug text not null unique,               -- 'asset_class_page'
  business_context text,                        -- 'lead_generation', 'ecommerce', 'both'
  purpose text,
  audience_mindset text,
  structure_template text,
  seo_requirements text,
  proof_elements text,
  cta_guidance text,
  internal_linking_rules text,
  quality_criteria text,
  common_mistakes text,
  example_references jsonb,                     -- URLs or stored examples
  word_count_range text,                        -- '2500-4500'
  primary_intent text,                          -- 'informational', 'transactional', 'commercial'
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- 4. AUDIENCE PROFILES
-- Detailed audience definitions per client.
-- A client may have multiple audiences.
-- ============================================================
create table audience_profiles (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  audience_name text not null,                  -- 'Property Managers'
  role_or_persona text,
  already_knows text,
  struggling_with text,
  skeptical_of text,
  responds_to text,
  reading_level text,
  content_preferences text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 5. CONTENT CHUNKS (RAG Knowledge Base)
-- Chunked, tagged content with vector embeddings for semantic search.
-- ============================================================
create table content_chunks (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  chunk_text text not null,
  context_prefix text,                          -- one-line summary for retrieval clarity
  source_article_title text,
  source_url text,
  source_date date,
  chunk_position int,                           -- position within original article
  topic_tags text[],
  keyword_tags text[],
  content_type_tag text,                        -- 'asset_class_page', 'blog_post', etc.
  intent_tag text,                              -- 'educating_on_asset_class', 'proving_results'
  asset_tags text[],                            -- 'statistic', 'comparison_table', 'case_study'
  funnel_stage text,                            -- 'top', 'mid', 'bottom'
  embedding vector(1536),                       -- OpenAI text-embedding-3-small
  created_at timestamptz not null default now()
);

-- Index for vector similarity search (cosine distance)
create index idx_content_chunks_embedding
  on content_chunks
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- Index for filtering by client before vector search
create index idx_content_chunks_client
  on content_chunks (client_id);

-- ============================================================
-- 6. CONTENT JOBS
-- Tracks every content generation/update request and its output.
-- ============================================================
create table content_jobs (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  content_type text not null,                   -- FK slug to content_types.type_slug
  target_keywords text[],
  topic text,
  mode text not null default 'new',             -- 'new' or 'update'
  source_url text,                              -- URL of existing page (update mode only)
  status text not null default 'pending',       -- 'pending','generating','ready_for_review','approved','published'
  coverage_level text,                          -- 'strong', 'partial', 'none'
  outline text,
  final_output text,
  output_url text,                              -- Google Doc link
  research_brief text,
  critique text,
  gap_research text,                            -- evidence package from Stage 5b
  model_used text,
  total_tokens int,
  estimated_cost decimal(10,4),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  published_at timestamptz
);

create index idx_content_jobs_client on content_jobs (client_id);
create index idx_content_jobs_status on content_jobs (status);

-- ============================================================
-- 7. PUBLISHED CONTENT MAP
-- Tracks what's live on each client's website.
-- Used for internal linking and content ecosystem awareness.
-- ============================================================
create table published_content_map (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  page_title text not null,
  page_url text not null,
  content_type text,                            -- 'blog_post', 'asset_class_page', etc.
  primary_keyword text,
  topic_tags text[],
  publish_date date,
  is_cornerstone boolean default false,
  created_at timestamptz not null default now(),

  constraint uq_published_content_url unique (client_id, page_url)
);

create index idx_published_content_client on published_content_map (client_id);

-- ============================================================
-- 8. EEAT ASSESSMENTS
-- Stores E-E-A-T assessments for existing content being updated.
-- Generated by Claude during the update pipeline's Stage 0a.
-- ============================================================
create table eeat_assessments (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references content_jobs(id) on delete cascade,
  client_id uuid not null references clients(id) on delete cascade,
  page_url text not null,
  scraped_content text,
  overall_score text,                           -- 'weak', 'moderate', 'strong'
  experience_assessment text,
  expertise_assessment text,
  authority_assessment text,
  trust_assessment text,
  strengths text[],
  weaknesses text[],
  gaps text[],
  actionable_suggestions text[],
  priority_actions text[],
  assessed_at timestamptz not null default now()
);

create index idx_eeat_job on eeat_assessments (job_id);

-- ============================================================
-- 9. GSC PAGE DATA
-- Google Search Console performance data per page.
-- Pulled via GSC API during the update pipeline's Stage 0b.
-- ============================================================
create table gsc_page_data (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  page_url text not null,
  date_range_start date not null,
  date_range_end date not null,
  total_clicks int,
  total_impressions int,
  average_ctr decimal(6,4),
  average_position decimal(6,2),
  top_queries jsonb,                            -- [{query, clicks, impressions, ctr, position}]
  declining_queries jsonb,                      -- [{query, position_change, clicks_change}]
  opportunity_queries jsonb,                    -- [{query, impressions, ctr, position}]
  fetched_at timestamptz not null default now()
);

create index idx_gsc_client_url on gsc_page_data (client_id, page_url);

-- ============================================================
-- HELPER FUNCTION: Vector similarity search for RAG
-- Call this from n8n to retrieve relevant chunks for a client.
-- ============================================================
create or replace function match_content_chunks(
  query_embedding vector(1536),
  match_client_id uuid,
  match_threshold float default 0.7,
  match_count int default 10
)
returns table (
  id uuid,
  chunk_text text,
  context_prefix text,
  source_article_title text,
  source_url text,
  topic_tags text[],
  keyword_tags text[],
  content_type_tag text,
  intent_tag text,
  asset_tags text[],
  funnel_stage text,
  similarity float
)
language sql stable
as $$
  select
    cc.id,
    cc.chunk_text,
    cc.context_prefix,
    cc.source_article_title,
    cc.source_url,
    cc.topic_tags,
    cc.keyword_tags,
    cc.content_type_tag,
    cc.intent_tag,
    cc.asset_tags,
    cc.funnel_stage,
    1 - (cc.embedding <=> query_embedding) as similarity
  from content_chunks cc
  where cc.client_id = match_client_id
    and 1 - (cc.embedding <=> query_embedding) > match_threshold
  order by cc.embedding <=> query_embedding
  limit match_count;
$$;

-- ============================================================
-- UPDATED_AT TRIGGER
-- Automatically update the updated_at column on row changes.
-- ============================================================
create or replace function update_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_clients_updated_at
  before update on clients
  for each row execute function update_updated_at();

create trigger trg_voice_profiles_updated_at
  before update on voice_profiles
  for each row execute function update_updated_at();

create trigger trg_content_types_updated_at
  before update on content_types
  for each row execute function update_updated_at();
